### ISSUE TITLE
cpp-build requires protobuf3

### ISSUE THREAD

**Issue by salrashid123** [googlei18n/libphonenumber#1807]
drive-by comment:

seems that cpp-build requires protobuf3 suport to to compile

as a repro

```
docker run -ti ubuntu /bin/bash
```

```
apt-get update
apt-get install -y maven curl git zip
apt-get install -y openjdk-8-jdk

curl -OL https://github.com/google/protobuf/releases/download/v3.2.0/protoc-3.2.0-linux-x86_64.zip
unzip protoc-3.2.0-linux-x86_64.zip -d protoc3
ln -s /protoc3/bin/protoc /usr/bin/protoc

git clone https://github.com/googlei18n/libphonenumber.git
cd libpphonenumber
mvn install
```

yields and error in compile

```
[INFO] 
[INFO] Libphonenumber build tools ......................... SUCCESS [  0.293 s]
[INFO] Libphonenumber common library for build tools ...... SUCCESS [  1.610 s]
[INFO] Libphonenumber C++ build tools ..................... FAILURE [  1.333 s]
[INFO] Libphonenumber Data tools .......................... SKIPPED
[INFO] Libphonenumber Java and JavaScript build tools ..... SKIPPED
[INFO] libphonenumber-parent .............................. SKIPPED
[INFO] libphonenumber ..................................... SKIPPED
[INFO] prefixmapper ....................................... SKIPPED
[INFO] carrier ............................................ SKIPPED
[INFO] geocoder ........................................... SKIPPED
[INFO] demo ............................................... SKIPPED
[INFO] libphonenumber-build-parent ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.476 s
[INFO] Finished at: 2017-06-23T03:28:44+00:00
[INFO] Final Memory: 21M/351M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project cpp-build: Compilation failure: Compilation failure:
[ERROR] /libphonenumber/tools/java/cpp-build/generated/com/google/i18n/phonenumbers/Phonemetadata.java:[10691,46] error: type GeneratedMessageLite does not take parameters
[ERROR] 
[ERROR] /libphonenumber/tools/java/cpp-build/generated/com/google/i18n/phonenumbers/Phonemetadata.java:[4561,46] error: type GeneratedMessageLite does not take parameters
[ERROR] 
[ERROR] /libphonenumber/tools/java/cpp-build/generated/com/google/i18n/phonenumbers/Phonemetadata.java:[311,46] error: type GeneratedMessageLite does not take parameters
[ERROR] 
[ERROR] /libphonenumber/tools/java/cpp-build/generated/com/google/i18n/phonenumbers/Phonemetadata.java:[2322,46] error: type GeneratedMessageLite does not take parameters
[ERROR] 
[ERROR] /libphonenumber/tools/java/cpp-build/generated/com/google/i18n/phonenumbers/Phonemetadata.java:[10699,40] error: cannot find symbol
```

which looks like a protbuf version error

so edit

```
tools/java/cpp-build/pom.xml
```

change:
```
    <dependency>
      <groupId>com.google.protobuf</groupId>
      <artifactId>protobuf-java</artifactId>
      <version>2.5.0</version>
    </dependency>
```
to 
```
<dependency>
    <groupId>com.google.protobuf</groupId>
    <artifactId>protobuf-java</artifactId>
    <version>3.3.1</version>
</dependency>
```

then with mvn install

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Libphonenumber build tools ......................... SUCCESS [  0.290 s]
[INFO] Libphonenumber common library for build tools ...... SUCCESS [  1.660 s]
[INFO] Libphonenumber C++ build tools ..................... SUCCESS [ 12.991 s]
[INFO] Libphonenumber Data tools .......................... SUCCESS [  1.644 s]
[INFO] Libphonenumber Java and JavaScript build tools ..... SUCCESS [  3.137 s]
[INFO] libphonenumber-parent .............................. SUCCESS [  8.666 s]
[INFO] libphonenumber ..................................... SUCCESS [ 40.810 s]
[INFO] prefixmapper ....................................... SUCCESS [  3.652 s]
[INFO] carrier ............................................ SUCCESS [  3.089 s]
[INFO] geocoder ........................................... SUCCESS [  3.865 s]
[INFO] demo ............................................... SUCCESS [  2.504 s]
[INFO] libphonenumber-build-parent ........................ SUCCESS [  0.003 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:22 min
[INFO] Finished at: 2017-06-23T03:34:58+00:00
[INFO] Final Memory: 99M/1155M
[INFO] ------------------------------------------------------------------------
```

**Comment by andyst** [comment]
Thanks for reporting the issue, @salrashid123 !

Odd, we haven't seen that before. I wonder why.
I guess it's because you installed protoc-3.2.0 (instead of some protoc version >= 2.4.0 but also version < 3).

For the time being, it's probably best if we change cpp/CMakeLists.txt and cpp/README to not only mention / check for PC_PROTOBUF protobuf>=2.4 but also that it's a 2.x version and not a 3.x version.

Unless someone sees a way to make it work with >= 2.4 incl. 3.x

/cc @keghani who knows more about our protobuf deps & version compatibility issues.

**Comment by salrashid123** [comment]
i neglected to state the reason i installed protoc3 was because what i get with
``` apt-get install protobuf-compiler``` is  2.6.1

```
# apt-cache policy protobuf-compiler
protobuf-compiler:
  Installed: 2.6.1-1.3
  Candidate: 2.6.1-1.3
  Version table:
 *** 2.6.1-1.3 500
        500 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status

root@0d07325b25bc:/libphonenumber# which protoc
/usr/bin/protoc
root@0d07325b25bc:/libphonenumber# protoc --version
libprotoc 2.6.1
```

if i used that, iI'd see:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project cpp-build: Compilation failure: Compilation failure:
[ERROR] /libphonenumber/tools/java/cpp-build/generated/com/google/i18n/phonenumbers/Phonemetadata.java:[587,30] error: cannot find symbol
[ERROR] 
[ERROR] could not parse error message:   symbol:   class ProtocolStringList
[ERROR] location: package com.google.protobuf
[ERROR] /libphonenumber/tools/java/cpp-build/generated/com/google/i18n/phonenumbers/Phonemetadata.java:112: error: cannot find symbol
[ERROR] com.google.protobuf.ProtocolStringList
```

... then i installedprotoc3 binary (thinking that ProtocolStringList came later version)...after that, the edit on the pom.yaml file...then it finally worked..  

..its really late here. i mayhave just done silly things..

**Comment by keghani** [comment]
The issue is with `mvn install`. We don't support that as a way to install the library and it's not in our docs anywhere.

### Background:
The issue is that the `cpp-build` module is not hermetic and depends on local dependencies.
This is why, in our continuous build config, we are using a special `travis` profile which doesn't actually build cpp-build:
https://github.com/googlei18n/libphonenumber/blob/88b902c/.travis.yml#L14
https://github.com/googlei18n/libphonenumber/blob/96d90b1/tools/java/pom.xml#L36

FWIW this behavior was introduced in #1348 as a necessary fix to be able to implement our soluton to stop bundling proto dependencies in the Maven artifacts.

### What you can do:
First, a question: What is your use case? Do you want to use the library? Port it?

To build `cpp-build` as-is, use libprotoc 2.5.0. Any other version will probably cause errors due to the dependency in [tools/java/cpp-build/pom.xml](https://github.com/googlei18n/libphonenumber/blob/96d90b1/tools/java/cpp-build/pom.xml#L156).

This is not an issue with people just wanting to use the library, so if what you're trying to do is port it, feel free to change the protoc dependency as you did above in your own port. We can't do this in our repository because whatever version we use, it will fail for people using another.

Why 2.5.0? 2.5.0 is still the latest version available from my package manager using `sudo apt-get install protobuf-compiler` and I can't reliably maintain the Maven setup with custom installations.

I'm happy to hear thoughts about how to make this build hermetic but don't know how to do this right now.

### Please respond:
@salrashid123 Please confirm if this unblocks you, otherwise how can I be more helpful?

@Andy I don't think we need to change `cpp/CMakeLists.txt` or the README. Those are about the C++ library, which is not the issue here IIUC (only the tools that build the C++ metadata).

**Comment by keghani** [comment]
I forgot to elaborate on `mvn install` not being supported, and "This is not an issue with people just wanting to use the library".

If you just want to use the library please see your chosen version's installation instructions:

C++: https://github.com/googlei18n/libphonenumber/blob/master/cpp/README
Java: https://github.com/googlei18n/libphonenumber#code
JS: https://github.com/googlei18n/libphonenumber/blob/master/javascript/README.md

**Comment by salrashid123** [comment]
@keghani   thanks!.  I actually dont' have a usecase to cite for doing this; I filed the bug on behalf of a customer thinking they had issues with normal _java_ builds.   (which is what led me to try and build it from scratch using the unconventional mvn approach.   

Anyway, please feel free to close this out unless we can derive any improvements to the build system given whatever excruciating steps i went through :)   

I've asked my customer (actually, both of ours on GCP), to file the bug separately about building the c++ part.

**Comment by keghani** [comment]
Great, thanks for confiming! I'll close this since there are no new issues with building cpp-build.
