### ISSUE TITLE
java.lang.NoClassDefFoundError: com.google.i18n.phonenumbers.nano.Phonemetadata$PhoneMetadata

### ISSUE THREAD

**Issue by angelkoh** [googlei18n/libphonenumber#1310]
Version used: 7.6.0.

The old codes was working with version 7.5.0

        PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();
        phoneUtil.parse(phoneNum, param_countryIso, protoPhoneNumber);

The following is the crash log.
 
>     E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
>                   Process: angel.support.phoneformat, PID: 25896
>                   java.lang.RuntimeException: An error occured while executing doInBackground()
>                       at android.os.AsyncTask$3.done(AsyncTask.java:300)
>                       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
>                       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
>                       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
>                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
>                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
>                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
>                       at java.lang.Thread.run(Thread.java:841)
>
>                    Caused by: java.lang.NoClassDefFoundError: com.google.i18n.phonenumbers.nano.Phonemetadata$PhoneMetadata
>                       at com.google.i18n.phonenumbers.MultiFileMetadataSourceImpl.getMetadataForRegion(MultiFileMetadataSourceImpl.java:71)
>                       at com.google.i18n.phonenumbers.PhoneNumberUtil.getMetadataForRegion(PhoneNumberUtil.java:2122)
>                       at com.google.i18n.phonenumbers.PhoneNumberUtil.parseHelper(PhoneNumberUtil.java:2981)
>                       at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:2842)
>                       at twitch.angelandroidapps.cnf2.domain.handlers.FormattingHandler.handleFormatting(FormattingHandler.java:180)
>                       at twitch.angelandroidapps.cnf2.domain.handlers.FormattingHandler.formatPhone(FormattingHandler.java:44)
>                       at twitch.angelandroidapps.cnf2.domain.handlers.AsyncFormatContactList.lambda$doBatchPopulateContactList$4(AsyncFormatContactList.java:140)
>                       at twitch.angelandroidapps.cnf2.domain.handlers.AsyncFormatContactList.access$lambda$0(AsyncFormatContactList.java)
>                       at twitch.angelandroidapps.cnf2.domain.handlers.AsyncFormatContactList$$Lambda$1.apply(Unknown Source)
>                       at com.innahema.collections.query.iterables.FilterIterable$1.hasNext(FilterIterable.java:50)
>                       at com.innahema.collections.query.queriables.Queryable.count(Queryable.java:1789)
>                       at com.innahema.collections.query.queriables.Queryable.count(Queryable.java:1796)
>                       at twitch.angelandroidapps.cnf2.domain.handlers.AsyncFormatContactList.doBatchPopulateContactList(AsyncFormatContactList.java:139)

**Comment by lararennie** [comment]
Hi,

Have you read the release notes? You have to change your deps with this version. 

Issue with instructions for gradle: #1306 
Email on our discussion mailing list with maven instructions: https://groups.google.com/forum/#!topic/libphonenumber-discuss/YzSNYll33Gc

I'll close this as it's not an issue with the library. Please consider joining
the [discussion
group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd
like to discuss this further.
